### ISSUE TITLE
Issues on Reverse Seat Selection 

### ISSUE THREAD

**Issue by ghost** [JinHuaTan/BusTicketingSystem#1]

**Comment by ghost** [comment]
Which color should I use on selected and not selected?

**Comment by LeeChanXian** [comment]
Should we include punishment if customer want to the seat to reversible?

**Comment by JinHuaTan** [comment]
@sooxl1996 i think white and red will suitable

**Comment by ghost** [comment]
@JinHuaTan I think white and red is not appropriate. The colors matching is kinda awkward. @LeeChanXian @justjaxy What u guys think?

**Comment by LeeChanXian** [comment]
@sooxl1996 i have to agree with you. Based on HCI, I think it is more appropriate for the colors matching is green and orange.

**Comment by ghost** [comment]
@LeeChanXian I agree!!! Any objection? @JinHuaTan @justjaxy , If no then we will proceed.

**Comment by JinHuaTan** [comment]
@LeeChanXian I agree with you

**Comment by justjaxy** [comment]
@sooxl1996 @LeeChanXian  I have no problem with it, i will stand neutral on this.
