### ISSUE TITLE
Initial database, domain, control for 4 tier object oriented 

### ISSUE THREAD

**Issue by ghost** [JinHuaTan/BusTicketingSystem#2]

**Comment by ghost** [comment]
As result from our meeting today, i will upload the excel from data dictionary for our domain here. If you guys have any update, please comment here and i will make appropriate changes.
[DataType-BusTicketing System.docx](https://github.com/JinHuaTan/BusTicketingSystem/files/626941/DataType-BusTicketing.System.docx)

**Comment by JinHuaTan** [comment]
@sooxl1996 very nice

**Comment by LeeChanXian** [comment]
@sooxl1996 i think you did good job for the data dictionary. I am satisfied with it.

**Comment by justjaxy** [comment]
@sooxl1996 The data type is quite clear and require no changes, I couldn't find any problem with. Good Job.
